package com.ferry.receiver.service

/**
 * FerryService stub for JVM test compilation.
 *
 * The real FerryService extends android.app.Service and depends on
 * NotificationCompat (AndroidX) and the R resource class (generated by AGP),
 * neither of which are available in the standalone JVM test runner.
 *
 * This stub provides only the companion object constants that are needed by
 * ServiceController (at compile time) and ServiceControllerTest / FerryServiceTest
 * (at test time). No Android lifecycle methods are present.
 */
class FerryService {
    companion object {
        const val ACTION_START   = "com.ferry.receiver.action.START"
        const val ACTION_STOP    = "com.ferry.receiver.action.STOP"
        const val ACTION_RESTART = "com.ferry.receiver.action.RESTART"
        const val NOTIFICATION_ID = 1
        const val CHANNEL_ID     = "ferry_service"
    }
}
